# Respiratory Health Classifier — Streamlit app

import os
import sys
import urllib.request

import numpy as np
import soundfile as sf
import librosa
import streamlit as st
from PIL import Image

APP_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, APP_DIR)

import predict  # noqa: E402
import preprocess  # noqa: E402

MODEL_URL = (
    "https://github.com/loukra/respiratory-sound-classification"
    "/releases/download/v1.0.0/ResNet.h5"
)
MODEL_PATH = os.path.join(APP_DIR, os.pardir, "models", "ResNet.h5")

TARGET_SR = 4000
# the model analyzes 8-second windows, so 8 s is the hard minimum;
# longer recordings yield several windows whose predictions are averaged
MIN_SECONDS = 8

st.set_page_config(
    page_title="Respiratory Health Classifier",
    page_icon="🫁",
    layout="centered",
)

with open(os.path.join(APP_DIR, "style.css")) as f:
    design = f.read()
st.html(f"""
<style>
{design}
</style>
<div class="hero">
  <h1>You Breathe, We Classify</h1>
  <p>AI-assisted screening from a few breaths of lung sound</p>
  <span class="dot"></span>
</div>
""")


def ensure_model_file():
    """Download the model from the GitHub release with a visible progress bar."""
    if os.path.exists(MODEL_PATH):
        return
    os.makedirs(os.path.dirname(MODEL_PATH), exist_ok=True)
    bar = st.progress(0.0, text="Preparing the analysis engine...")

    def hook(blocks, block_size, total_size):
        if total_size > 0:
            pct = min(blocks * block_size / total_size, 1.0)
            bar.progress(pct, text=f"Preparing the analysis engine... {int(pct * 100)} %")

    urllib.request.urlretrieve(MODEL_URL, MODEL_PATH, reporthook=hook)
    bar.empty()


@st.cache_resource(show_spinner="Starting the analysis engine...")
def load_model():
    import keras
    model = keras.models.load_model(MODEL_PATH, compile=False)
    # dummy inference so TF traces the graph now, not on the first user request
    model.predict(np.zeros((1, 224, 224, 3)), verbose=0)
    return model


def result_card(y_pred):
    healthy = y_pred > 0.5
    pct = 5 * round((y_pred if healthy else 1 - y_pred) * 100 / 5)
    cls = "healthy" if healthy else "diseased"
    text = (
        "estimated probability of <b>healthy airways</b>"
        if healthy
        else "estimated probability of <b>abnormal airways</b> — "
             "we recommend consulting a physician"
    )
    st.html(f"""
<div class="result-card {cls}">
  <div class="result-pct">≈ {pct} %</div>
  <div class="result-text">{text}</div>
  <div class="gauge"><div class="gauge-fill" style="width:{pct}%"></div></div>
  <div class="result-note">This screening result is generated by an AI model and is
  not a medical diagnosis. If you have symptoms or concerns, consult a physician.</div>
</div>
""")


with st.sidebar:
    st.title("Respiratory Health Classifier")
    st.markdown(
        "Records your breathing through the microphone and estimates the "
        "probability of healthy airways with a deep neural network trained "
        "on clinical lung auscultation data."
    )
    st.markdown("#### Getting a reliable recording")
    st.markdown("""
1. Place the microphone directly on the bare skin of your chest, at the position shown below.
2. Press the microphone button to start.
3. Breathe deeply in and out through your mouth.
4. After at least 8 seconds, stop the recording — the analysis starts automatically. Longer recordings (15–20 s) give a more reliable result.
""")
    st.image(
        Image.open(os.path.join(APP_DIR, "adam.jpg")),
        caption="Recommended microphone position (illustration: A.D.A.M.)",
    )


ensure_model_file()
model = load_model()

audio = st.audio_input(f"Record your breathing for at least {MIN_SECONDS} seconds")

if audio is not None:
    data_origin, samplerate = sf.read(audio)

    # recordings may be mono or stereo depending on the device
    wav = data_origin[:, 0] if data_origin.ndim > 1 else data_origin

    data = librosa.resample(y=wav, orig_sr=samplerate, target_sr=TARGET_SR)
    duration = data.shape[0] / TARGET_SR

    if duration >= MIN_SECONDS:
        with st.spinner('Analyzing your breathing...'):
            preprocessor = preprocess.AudioPreprocessor()
            predictor = predict.MyPredictor(model, preprocessor)

            # trim to a whole number of seconds
            data = data[: int(TARGET_SR * np.floor(duration))]
            y_pred = predictor.predict(data)

        result_card(y_pred)
    else:
        st.warning(
            f"Your recording was {duration:.0f} seconds. Please record for at least "
            f"{MIN_SECONDS} seconds so the analysis has enough breathing cycles to work with."
        )

st.html("""
<div class="app-footer">
  Built with TensorFlow &amp; Streamlit ·
  <a href="https://github.com/loukra/respiratory-sound-classification">Model &amp; code on GitHub</a>
</div>
""")
